$wallpaper = /home/athe/.config/wallpapers/Anime - Favorite Forrest - Day.jpg
$background = rgb(0F1017)
$foreground = rgb(E2F2FB)
$color0 = rgb(37383F)
$color1 = rgb(E2A7D7)
$color2 = rgb(F3A4D4)
$color3 = rgb(D1BFDA)
$color4 = rgb(CBD488)
$color5 = rgb(D3D87C)
$color6 = rgb(AEDBF4)
$color7 = rgb(CEE4F1)
$color8 = rgb(90A0A9)
$color9 = rgb(E2A7D7)
$color10 = rgb(F3A4D4)
$color11 = rgb(D1BFDA)
$color12 = rgb(CBD488)
$color13 = rgb(D3D87C)
$color14 = rgb(AEDBF4)
$color15 = rgb(CEE4F1)
