$wallpaper = /home/athe/.config/wallpapers/Anime - Spirited Away - Night.jpg
$background = rgb(1E1F20)
$foreground = rgb(F7FAFD)
$color0 = rgb(444646)
$color1 = rgb(313B3D)
$color2 = rgb(6E7F8F)
$color3 = rgb(D1614B)
$color4 = rgb(BA8661)
$color5 = rgb(92A3AB)
$color6 = rgb(E7F2F8)
$color7 = rgb(EAF0F3)
$color8 = rgb(A4A8AA)
$color9 = rgb(313B3D)
$color10 = rgb(6E7F8F)
$color11 = rgb(D1614B)
$color12 = rgb(BA8661)
$color13 = rgb(92A3AB)
$color14 = rgb(E7F2F8)
$color15 = rgb(EAF0F3)
