#!/usr/bin/env bash

# Run the given command in a new terminal and keep that terminal open afterward.
# Useful for commands launched from a GUI/keybinding where output would otherwise disappear.

$USER_TERMINAL -e bash -c "$*; tput setaf 5 bold; read -p 'Press any key to exit.' -s -n 1"
