[theme]
background = "#17161C"
primary = "#B2FAFC"
secondary = "#60A7A9"
title = "#538AB2"
playing = "#538AB2"
playing_selected = "#538AB2"
playing_bg = "#17161C"
highlight = "#B2FAFC"
highlight_bg = "#60A7A9"
highlight_inactive_bg = "#424149"
error = "#B2FAFC"
error_bg = "#678563"
statusbar = "#17161C"
statusbar_progress = "#538AB2"
statusbar_progress_bg = "#60A7A9"
statusbar_bg = "#538AB2"
cmdline = "#B2FAFC"
cmdline_bg = "#17161C"
search_match = "#678563"
