[theme]
background = "#0F1017"
primary = "#E2F2FB"
secondary = "#90A0A9"
title = "#F3A4D4"
playing = "#F3A4D4"
playing_selected = "#F3A4D4"
playing_bg = "#0F1017"
highlight = "#E2F2FB"
highlight_bg = "#90A0A9"
highlight_inactive_bg = "#37383F"
error = "#E2F2FB"
error_bg = "#E2A7D7"
statusbar = "#0F1017"
statusbar_progress = "#F3A4D4"
statusbar_progress_bg = "#90A0A9"
statusbar_bg = "#F3A4D4"
cmdline = "#E2F2FB"
cmdline_bg = "#0F1017"
search_match = "#E2A7D7"
