use_nerdfont = true
# notify = true

# [theme]
# background = "#131314"
# primary = "#F9E7CF"
# secondary = "#A7947D"
# title = "#E379B1"
# playing = "#E379B1"
# playing_selected = "#E379B1"
# playing_bg = "#131314"
# highlight = "#F9E7CF"
# highlight_bg = "#A7947D"
# highlight_inactive_bg = "#3B3A3B"
# error = "#F9E7CF"
# error_bg = "#E57B96"
# statusbar = "#131314"
# statusbar_progress = "#E379B1"
# statusbar_progress_bg = "#A7947D"
# statusbar_bg = "#E379B1"
# cmdline = "#F9E7CF"
# cmdline_bg = "#131314"
# search_match = "#E57B96"
