# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/


#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/config/environment_variables.conf
# See https://wiki.hyprland.org/Configuring/Environment-variables/


################
### MONITORS ###
################
source = ~/.config/hypr/monitors.conf
# See https://wiki.hyprland.org/Configuring/Monitors/


###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/config/defaults.conf
# See https://wiki.hyprland.org/Configuring/Keywords/


#################
### AUTOSTART ###
#################
source = ~/.config/hypr/config/autostart.conf


#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/config/look_and_feel.conf


#############
### INPUT ###
#############
source = ~/.config/hypr/config/input.conf


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/config/keybinds.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/config/windows_and_workspaces.conf
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
