local vars = require("config.defaults")

hl.on("hyprland.start", function()
  hl.exec_cmd("quickshell --daemonize")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd(vars.sessionTarget)
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("xsettingsd")
  hl.exec_cmd(vars.themeToggle .. " apply")

  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")

  hl.exec_cmd(vars.idleHandler)
end)

hl.on("hyprland.shutdown", function()
  hl.exec_cmd("pkill quickshell")
  hl.exec_cmd("pkill awww-daemon")
  hl.exec_cmd("systemctl --user stop hyprland-session.target")
  hl.exec_cmd("systemctl --user stop hyprpolkitagent")
  hl.exec_cmd("pkill xsettingsd")
  hl.exec_cmd("pkill wl-paste")
  hl.exec_cmd("pkill swayidle")
end)
