#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# exec-once = nm-applet --indicator &
exec-once = quickshell &
exec-once = swww-daemon &
exec-once = swaync &
exec-once = systemctl --user start hyprpolkitagent &
exec-once = hyprctl setcursor breeze-dark 24 &


# CLIPBOARD STUFF
exec-once = wl-paste --type text --watch cliphist store & # Stores only text data
exec-once = wl-paste --type image --watch cliphist store & # Stores only image data

# Slow app launch Fix - CachyOS
# exec-once = systemctl --user import-environment &
# exec-once = hash dbus-update-activation-environment 2>/dev/null &
# exec-once = dbus-update-activation-environment --systemd &

# Idle Configuration - CachyOS
exec-once = $idleHandler


#################
### SHUTDOWN  ###
#################

exec-shutdown = pkill quickshell
exec-shutdown = pkill swww-daemon
exec-shutdown = swaync-client -q
exec-shutdown = systemctl --user stop hyprpolkitagent
exec-shutdown = pkill wl-paste
exec-shutdown = pkill swayidle
