#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

env = GDK_BACKEND,wayland,x11
env = GTK_RC_FILES,/etc/gtk/gtkrc:$HOME/.config/gtkrc
env = GTK2_RC_FILES,/etc/gtk-2.0/gtkrc:$HOME/.config/gtkrc

env = KDE_SESSION_VERSION,6
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,kde
env = QT_QUICK_CONTROLS_STYLE,org.kde.desktop
env = QT_STYLE_OVERRIDE,Breeze

env = XCURSOR_THEME,breeze_cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = HYPR_CONFIG_PATH,$HOME/.config/hypr
env = HYPR_SCRIPTS,$HOME/.config/hypr/scripts
env = USER_TERMINAL,ghostty
env = ALT_TERMINAL,alacritty
env = TERMINAL,ghostty
env = EDITOR,nvim
env = VISUAL,nvim
env = BROWSER,xdg-open

# env = ELECTRON_OZONE_PLATFORM_HINT,auto
# env = GTK_THEME,Breeze-Dark


# UNUSED #
# env = GTK_THEME, adw-gtk3-dark:dark
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDER_LIBRARY_NAME,nvidia
#
# env = LANG,en_US.UTF-8
# env = LC_ALL,en_US.UTF-8
# env = HYPRCURSOR_THEME,Breeze
