#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = LANG,en_US.UTF-8
env = LC_ALL,en_US.UTF-8
env = XCURSOR_THEME,Breeze
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Breeze
env = HYPRCURSOR_SIZE,24

env = HYPR_CONFIG_PATH,$HOME/.config/hypr
env = HYPR_SCRIPTS,$HOME/.config/hypr/scripts

env = USER_TERMINAL,alacritty
env = XDG_CURRENT_DESKTOP,Hyprland
env = GTK_RC_FILES,/etc/gtk/gtkrc:$HOME/.gtkrc:$HOME/.config/gtkrc
env = GTK2_RC_FILES,/etc/gtk-2.0/gtkrc:$HOME/.gtkrc-2.0:$HOME/.config/gtkrc-2.0
env = GTK_THEME,Breeze:dark
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
# env = GTK_THEME, adw-gtk3-dark:dark
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDER_LIBRARY_NAME,nvidia
