#!/usr/bin/env bash
set -euo pipefail

state_file="${HOME}/.config/hypr/config/opacity-toggle.conf"
override_rule="opacity 1.0 override 1.0 override 1.0 override, match:class .*"

notify() {
  if command -v notify-send >/dev/null 2>&1; then
    notify-send "Hyprland opacity" "$1"
  fi
}

if [ -s "$state_file" ]; then
  : > "$state_file"
  hyprctl reload >/dev/null
  notify "Configured opacity rules restored"
  exit 0
fi

printf '# Generated by toggle-opacity.sh\nwindowrule = %s\n' "$override_rule" > "$state_file"
hyprctl keyword windowrule "$override_rule" >/dev/null
notify "Opacity rules disabled"
