##### COLOR SCHEME #####
# Default colors
# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#EBCBE7"
# cursor = "#47FF9C"

[colors.primary]
background = "#0F1017"
foreground = "#E2F2FB"

[colors.normal]
black = "#37383F"
red = "#D3D87C"
green = "#F3A4D4"
yellow = "#D1BFDA"
blue = "#CBD488"
magenta = "#D3D87C"
cyan = "#AEDBF4"
white = "#CEE4F1"

[colors.bright]
black = "#90A0A9"
red = "#D3D87C"
green = "#F3A4D4"
yellow = "#D1BFDA"
blue = "#CBD488"
magenta = "#D3D87C"
cyan = "#AEDBF4"
white = "#CEE4F1"
