[theme]
background = "{{background}}"
primary = "{{foreground}}"
secondary = "{{color8}}"
title = "{{color2}}"
playing = "{{color2}}"
playing_selected = "{{color10}}"
playing_bg = "{{background}}"
highlight = "{{foreground}}"
highlight_bg = "{{color8}}"
highlight_inactive_bg = "{{color0}}"
error = "{{foreground}}"
error_bg = "{{color1}}"
statusbar = "{{background}}"
statusbar_progress = "{{color2}}"
statusbar_progress_bg = "{{color8}}"
statusbar_bg = "{{color2}}"
cmdline = "{{foreground}}"
cmdline_bg = "{{background}}"
search_match = "{{color1}}"
